### PR TITLE
Fix adding ST_MODPROC case in function mkvarref()

### LINKED ISSUE #1016: dbcsr: flang did not notice that pure function defined later in the 'contains' section is pure
Consider the following piece of Fortran code:

```
module mymod
  implicit none
  private
  public :: func, other_func
  type :: foo
    integer :: mydim
  end type

contains

subroutine func(tparam, oparam)
  type(foo), intent(in) :: tparam
  integer, dimension(other_func(tparam, 1)), intent(out), optional :: oparam

  oparam = 42
end subroutine

pure function other_func(tparam, idim)
  type(foo), intent(in) :: tparam
  integer, intent(in) :: idim
  integer :: other_func

  other_func = min(tparam%mydim, idim)
end function

end module
```

Note that gfortran can compile this code, while flang can not:

```
F90-S-0084-Illegal use of symbol other_func  (mymod.f90: 13)
  0 inform,   0 warnings,   1 severes, 0 fatal for func
```

Yet when the pure function `other_func` definition is moved before it is used (in a place where a pure function should be called), flang is able to compile it:

```
contains

pure function other_func(tparam, idim)
  type(foo), intent(in) :: tparam
  integer, intent(in) :: idim
  integer :: other_func

  other_func = min(tparam%mydim, idim)
end function

subroutine func(tparam, oparam)
  type(foo), intent(in) :: tparam
  integer, dimension(other_func(tparam, 1)), intent(out), optional :: oparam

  oparam = 42
end subroutine
```

### PR DESCRIPTION
**Pull request by abrahamtovarmob**
Adding ST_MODPROC to switch() options in mkvarref() to fix an issue
relating Pure Function not being properly detected.

The issue occours because the pure function type has assignated
ST_MODPROC and is not recognized.
In the case of the Workaround, the type is ST_PROC. Debug reveald
that the assignated types are correct, but the probem is that
ST_MODPROC has no action defined, hence an error in the compiler.
The soluton is to add ST_MODPROC into the same section as ST_PROC
in order to perfom the same actions

Fixes #1016

### CODE REVIEW

**Comment by michalpasztamobica** [comment]
@pawosm-arm , would you please double check the f90 test? It is a little bit simplified, compared to your reproducer (the type of the tparam is not `foo`, but `integer` instead). Abraham was still able to reproduce the issue without the fix. We had trouble using a private type from the main program, to be honest :)

**Comment by pawosm-arm** [comment]
I'll build dbcsr and cp2k with it to make sure cp2k can make use of the dbcsr modules without any workarounds we had to use. That should prove this fix is ok.

**Comment by pawosm-arm** [comment]
With this fix, I've successfully managed to build dbcsr with the corresponding workaround reverted (namely, CP2K can make use of it). Also, number of passing test cases did not drop. Therefore I can say that this fix does its job.

**Review by pawosm-arm — APPROVED** [review]

**Comment by pawosm-arm** [comment]
@bryanpkc this is something we were waiting for for some long time. Can you look at this, please?

**Comment by kiranchandramohan** [comment]
Please provide a description in the commit message. You can consider moving some of the points mentioned in 1016 to the description.

**Comment by abrahamtovarmob** [comment]
> Please provide a description in the commit message. You can consider moving some of the points mentioned in 1016 to the description.

Done. Can you approve the workflow for CI to be triggered?

File: test/f90_correct/src/pure_function.f90 [hunk 1]
```diff
@@ -0,0 +1,44 @@
+module mymod
```
Comment (bryanpkc) [inline test/f90_correct/src/pure_function.f90:1]: Could you add a comment in this test case to indicate that this is a reproducer for #1016, and that the procedures `func` and `other_func` should never be reordered?

Comment (bryanpkc) [reply test/f90_correct/src/pure_function.f90:1]: Alternatively, rename the test case to `issue1016.f90`.

Also, I suggest using more unique names for the module `mymod` and the program `test`. We have run into test failures previously when module names collided.

Comment (pawosm-arm) [reply test/f90_correct/src/pure_function.f90:1]: I wouldn't rename the file to point at github issue. Let's not create a precedence.

Comment (bryanpkc) [reply test/f90_correct/src/pure_function.f90:1]: Would you object to mentioning the issue inside a comment?

Comment (abrahamtovarmob) [reply test/f90_correct/src/pure_function.f90]: Suggested changes added to the test. Also rebase for new master commits

**Comment by abrahamtovarmob** [comment]
Can somebody approve the workflow? since I'm new I need a contributor to approve

**Review by bryanpkc — APPROVED** [review]
